server:
  port: ${PORT:22000}

spring:
#db pool 以下配置根据环境更改
  datasource:
  #数据库名称
    db-name: atom

# REDIS (RedisProperties)
  redis:
    database: 31

  kafka:
    default:
      topic: atom.test
    consumer:
      topics: ${spring.kafka.default.topic}

